services:
  pgadmin4:
    image: dpage/pgadmin4:9.0.0
    ports:
    - 8080:80
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@example.com
    - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
    - pgadmin4:/var/lib/pgadmin

  postgres_v14_primary:
    image: postgres:14.9-alpine3.18
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    volumes:
    - postgres_v14_primary:/var/lib/postgresql/data

  postgres_v16_primary:
    image: postgres:17.4-alpine3.21
    ports:
    - 5433:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    volumes:
    - postgres_v16_primary:/var/lib/postgresql/data

volumes:
  pgadmin4:
  postgres_v14_primary:
  postgres_v16_primary:
